import '/models/station_details.dart';

class StationData {
  static final Map<String, StationDetails> stations = {
    'NS1': StationDetails(
      code: 'NS1',
      name: 'Jurong East',
      imageUrl: 'assets/ns1.jpg',
      address: '10 Jurong East Street 12, Singapore 609690',
      latitude: 1.333208,
      longitude: 103.742017,
      nearbyAmenities: [
        'JCube',
        'Jurong Regional Library',
        'Jurong East Bus Interchange',
        'Westgate',
        'Jem',
      ],
    ),
    'NS2': StationDetails(
      code: 'NS2',
      name: 'Bukit Batok',
      imageUrl: 'assets/ns2.jpg',
      address: '930 Bukit Batok West Avenue 3, Singapore 659930',
      latitude: 1.349012,
      longitude: 103.749660,
      nearbyAmenities: [
        'West Mall',
        'Bukit Batok Bus Interchange',
        'Bukit Batok Polyclinic',
      ],
    ),
    'NS3': StationDetails(
      code: 'NS3',
      name: 'Bukit Gombak',
      imageUrl: 'assets/ns3.jpg',
      address: '802 Bukit Batok West Avenue 5, Singapore 659083',
      latitude: 1.359043,
      longitude: 103.751863,
      nearbyAmenities: [
        'Bukit Gombak Stadium',
        'Little Guilin',
        'Hong Kah North Community Club',
      ],
    ),
    'NS4': StationDetails(
      code: 'NS4',
      name: 'Choa Chu Kang',
      imageUrl: 'assets/ns4.jpg',
      address: '10 Choa Chu Kang Avenue 4, Singapore 689810',
      latitude: 1.385420,
      longitude: 103.744317,
      nearbyAmenities: [
        'Lot One Shoppers Mall',
        'Choa Chu Kang Bus Interchange',
        'South View Primary School',
      ],
    ),
    'NS5': StationDetails(
      code: 'NS5',
      name: 'Yew Tee',
      imageUrl: 'assets/ns5.jpg',
      address: '61 Choa Chu Kang Drive, Singapore 689715',
      latitude: 1.397383,
      longitude: 103.747316,
      nearbyAmenities: [
        'Yew Tee Point',
        'Yew Tee Community Club',
        'Yew Tee Square',
      ],
    ),
    'NS7': StationDetails(
      code: 'NS7',
      name: 'Kranji',
      imageUrl: 'assets/ns7.jpg',
      address: '960 Kranji Road, Singapore 739473',
      latitude: 1.425302,
      longitude: 103.762049,
      nearbyAmenities: [
        'Singapore Turf Club',
        'Kranji War Memorial',
        'Sungei Kadut Industrial Estate',
      ],
    ),
    'NS8': StationDetails(
      code: 'NS8',
      name: 'Marsiling',
      imageUrl: 'assets/ns8.jpg',
      address: '71 Woodlands Avenue 3, Singapore 739044',
      latitude: 1.432636,
      longitude: 103.774033,
      nearbyAmenities: [
        'Marsiling Mall',
        'Woodlands Stadium',
        'Marsiling Park',
      ],
    ),
    'NS9': StationDetails(
      code: 'NS9',
      name: 'Woodlands',
      imageUrl: 'assets/ns9.jpg',
      address: '30 Woodlands Avenue 2, Singapore 738343',
      latitude: 1.436980,
      longitude: 103.786483,
      nearbyAmenities: [
        'Causeway Point',
        'Woodlands Regional Library',
        'Woodlands Civic Centre',
      ],
    ),
    'NS10': StationDetails(
      code: 'NS10',
      name: 'Admiralty',
      imageUrl: 'assets/ns10.jpg',
      address: '70 Woodlands Avenue 7, Singapore 738344',
      latitude: 1.440689,
      longitude: 103.800933,
      nearbyAmenities: [
        'Admiralty Place',
        'Woodlands Swimming Complex',
        'Republic Polytechnic',
      ],
    ),
    'NS11': StationDetails(
      code: 'NS11',
      name: 'Sembawang',
      imageUrl: 'assets/ns11.jpg',
      address: '11 Sembawang Way, Singapore 758091',
      latitude: 1.449025,
      longitude: 103.820153,
      nearbyAmenities: [
        'Sun Plaza',
        'Sembawang Shopping Centre',
        'Sembawang Hot Spring Park',
      ],
    ),
    'NS12': StationDetails(
      code: 'NS12',
      name: 'Canberra',
      imageUrl: 'assets/ns12.jpg',
      address: '27 Canberra Link, Singapore 756972',
      latitude: 1.443255,
      longitude: 103.829857,
      nearbyAmenities: [
        'Canberra Plaza',
        'Sembawang Springs Estate',
        'Yishun Dam',
        'Sembawang Park',
        'Canberra Community Club',
      ],
    ),
    'NS13': StationDetails(
      code: 'NS13',
      name: 'Yishun',
      imageUrl: 'assets/ns13.jpg',
      address: '301 Yishun Avenue 2, Singapore 769093',
      latitude: 1.429464,
      longitude: 103.835239,
      nearbyAmenities: [
        'Northpoint City',
        'Khoo Teck Puat Hospital',
        'Yishun Park',
      ],
    ),
    'NS14': StationDetails(
      code: 'NS14',
      name: 'Khatib',
      imageUrl: 'assets/ns14.jpg',
      address: '201 Yishun Avenue 2, Singapore 769092',
      latitude: 1.417167,
      longitude: 103.832969,
      nearbyAmenities: [
        'Yishun Stadium',
        'SAFRA Yishun',
        'Lower Seletar Reservoir Park',
      ],
    ),
    'NS15': StationDetails(
      code: 'NS15',
      name: 'Yio Chu Kang',
      imageUrl: 'assets/ns15.jpg',
      address: '3000 Ang Mo Kio Avenue 8, Singapore 569813',
      latitude: 1.381906,
      longitude: 103.844817,
      nearbyAmenities: [
        'Yio Chu Kang Stadium',
        'Yio Chu Kang Swimming Complex',
        'Ang Mo Kio Industrial Park',
      ],
    ),
    'NS16': StationDetails(
      code: 'NS16',
      name: 'Ang Mo Kio',
      imageUrl: 'assets/ns16.jpg',
      address: '2450 Ang Mo Kio Avenue 8, Singapore 569811',
      latitude: 1.370017,
      longitude: 103.849617,
      nearbyAmenities: [
        'AMK Hub',
        'Ang Mo Kio Town Garden West',
        'Ang Mo Kio Public Library',
        'Anderson Secondary School',
      ],
    ),
    'NS17': StationDetails(
      code: 'NS17',
      name: 'Bishan',
      imageUrl: 'assets/ns17.jpg',
      address: '17 Bishan Place, Singapore 579842',
      latitude: 1.351236,
      longitude: 103.848679,
      nearbyAmenities: [
        'Junction 8',
        'Bishan Public Library',
        'Bishan Stadium',
        'Bishan-Ang Mo Kio Park',
      ],
    ),
    'NS18': StationDetails(
      code: 'NS18',
      name: 'Braddell',
      imageUrl: 'assets/ns18.jpg',
      address: '900 Toa Payoh North, Singapore 319774',
      latitude: 1.340339,
      longitude: 103.847122,
      nearbyAmenities: [
        'Mount Alvernia Hospital',
        'MacRitchie Reservoir Park',
        'Toa Payoh Stadium',
      ],
    ),
    'NS19': StationDetails(
      code: 'NS19',
      name: 'Toa Payoh',
      imageUrl: 'assets/ns19.jpg',
      address: '510 Lorong 6 Toa Payoh, Singapore 319398',
      latitude: 1.332703,
      longitude: 103.847822,
      nearbyAmenities: [
        'Toa Payoh Hub',
        'Toa Payoh Public Library',
        'Toa Payoh Central Community Club',
      ],
    ),
    'NS20': StationDetails(
      code: 'NS20',
      name: 'Novena',
      imageUrl: 'assets/ns20.jpg',
      address: '250 Thomson Road, Singapore 307642',
      latitude: 1.320441,
      longitude: 103.843375,
      nearbyAmenities: [
        'Velocity@Novena Square',
        'Square 2',
        'Tan Tock Seng Hospital',
      ],
    ),
    'NS21': StationDetails(
      code: 'NS21',
      name: 'Newton',
      imageUrl: 'assets/ns21.jpg',
      address: '49 Scotts Road, Singapore 228234',
      latitude: 1.312956,
      longitude: 103.838442,
      nearbyAmenities: [
        'Newton Food Centre',
        'Newton Life Church',
        'Hotel Royal Newton',
      ],
    ),
    'NS22': StationDetails(
      code: 'NS22',
      name: 'Orchard',
      imageUrl: 'assets/ns22.jpg',
      address: '437 Orchard Road, Singapore 238878',
      latitude: 1.304314,
      longitude: 103.831939,
      nearbyAmenities: [
        'ION Orchard',
        'Ngee Ann City',
        'Wisma Atria',
        'Tangs Plaza',
      ],
    ),
    'NS23': StationDetails(
      code: 'NS23',
      name: 'Somerset',
      imageUrl: 'assets/ns23.jpg',
      address: '1 Somerset Road, Singapore 238162',
      latitude: 1.300514,
      longitude: 103.839028,
      nearbyAmenities: [
        '313@Somerset',
        'Orchard Central',
        'TripleOne Somerset',
      ],
    ),
    'NS24': StationDetails(
      code: 'NS24',
      name: 'Dhoby Ghaut',
      imageUrl: 'assets/ns24.jpg',
      address: '11 Orchard Road, Singapore 238826',
      latitude: 1.299156,
      longitude: 103.845736,
      nearbyAmenities: [
        'Plaza Singapura',
        'The Cathay',
        'SOTA',
        'SMU',
      ],
    ),
    'NS25': StationDetails(
      code: 'NS25',
      name: 'City Hall',
      imageUrl: 'assets/ns25.jpg',
      address: '150 North Bridge Road, Singapore 179100',
      latitude: 1.293239,
      longitude: 103.852219,
      nearbyAmenities: [
        'Raffles City',
        'St. Andrews Cathedral',
        'National Gallery Singapore',
      ],
    ),
    'NS26': StationDetails(
      code: 'NS26',
      name: 'Raffles Place',
      imageUrl: 'assets/ns26.jpg',
      address: '5 Raffles Place, Singapore 048618',
      latitude: 1.283881,
      longitude: 103.851533,
      nearbyAmenities: [
        'UOB Plaza',
        'One Raffles Place',
        'The Fullerton Hotel',
      ],
    ),
    'NS27': StationDetails(
      code: 'NS27',
      name: 'Marina Bay',
      imageUrl: 'assets/ns27.jpg',
      address: '21 Marina Station Road, Singapore 018994',
      latitude: 1.276097,
      longitude: 103.854675,
      nearbyAmenities: [
        'Marina Bay Sands',
        'Gardens by the Bay',
        'Marina Bay Financial Centre',
      ],
    ),
    'NS28': StationDetails(
      code: 'NS28',
      name: 'Marina South Pier',
      imageUrl: 'assets/ns28.jpg',
      address: '31 Marina Coastal Drive, Singapore 018988',
      latitude: 1.271422,
      longitude: 103.863817,
      nearbyAmenities: [
        'Marina South Pier',
        'Marina Coastal Drive',
        'Marina Barrage',
      ],
    ),
  };

  static StationDetails getStationDetailsOrDefault(String code) {
    return stations[code] ?? _getDefaultDetails(code);
  }

  static StationDetails _getDefaultDetails(String code) {
    return StationDetails(
      code: code,
      name: 'Station',
      imageUrl: 'assets/default_station.jpg',
      address: 'Address not available',
      latitude: 0,
      longitude: 0,
      nearbyAmenities: [],
    );
  }
}
